### PR TITLE
Updated dox task to support grunt 0.4rc5

### PR DESCRIPTION
**Pull request by phun-ky**

### CODE REVIEW

**Comment by phun-ky** [comment]
FYI, latest pull request works with the Windows `type` command ;)

**Comment by phun-ky** [comment]
Added some output cleaning and passing of options

**Comment by phun-ky** [comment]
@mattmcmanus status on this pull request?

**Comment by mattmcmanus** [comment]
No yet. Haven't had a chance to play with it yet. I'll get to it as soon as
I can.

**Comment by mattmcmanus** [comment]
Hey @phunk-ky, I completely spaced on this before I did some hacking tonight. Would you mind fetching the last master and seeing what is conflicting? I cleaned things up a bit and updated it to work with dox-foundation v.04

**Comment by phun-ky** [comment]
Seems like your latest rewrite broke a bunch of things. I suggest we discuss this a bit, maybe ignore this fork, since dox-foundation currently lacks certain features.

With the old rewrite ( the firs by me ), one single file was generated with docs from dox-foundation. The result was poor and lacked links to files that has been generated.

The new rewrite (for dox-foundation v0.4 support) forced users to only send in one directory with no subdirectories with only support for "grunt-in-project-related-files", not absolute paths or relative paths to another CWD. The resulting html files were a great deal better, but it took a _LOT_ of tweaking in the code of dox-foundation to make it work. (Could be more relevant to a Windows environment)

For now, I currently suggest that you can just switch `this.expandFiles(this.file.src)` with `this.filesSrc` to make it grunt v0.4 compatible, and after that I hope we can talk about how to solve the other issues.

**Comment by phun-ky** [comment]
**Regarding latest update here**

After a bit of thinking around how grunt-dox should pass on the source folder to dox-foundation, I found that the best alternative yet is to just treat the incoming src folder as a folder and pass that folder directly to dox-foundation. If a user wants to dox more folders, use grunt-dox as a multi task ( because that's what it is).

Dox-foundation currently does not support sending several directories for parsing, and I felt that the assumption to parse the parent dir of `lib/**/*.js` would not suit most use cases. A user, with given example syntax, would assume that every file and subdirectories under `lib/` would be doxed. And that's exactly what grunt-dox do. But if a user have `../project/js/src/**/*.js`, or `project/js/src/**/*.js` for that matter, all folders and subdirectories under `project` would get doxxed, and not all folders and subdirectories under `project/js/src` as the user states!

Ideally, dox-foundation would accept a comma separated file list with absolute or relative paths with the `--source` flag, this will solve all user input imho.

Please, give me some feedback on this, and I will see if I can make the required changes in dox-foundation to support this, if I have the time.

**Comment by mattmcmanus** [comment]
You make two great points. 
1. the parentDir function is a perfect example of complete over-engineering. I realized that the other night and hadn't got around to tearing it out. 
2. There is a disconnect between this being a multitask and dox-foundation not really supporting multiple sources. In the new example that you provided in the readme, what is the final result look like?

Hopefully I'll get a chance to pull down this change locally and play around with it.

**Comment by phun-ky** [comment]
Working on the mulitdir support as we speak ;-) 

Mvh / Regards 
Alexander Vassbotn Røyne-Helgesen 
alexander@phun -ky.net
0047 997 98 910
http://phun-ky.net
http://no.linkedin.com/in/alexanderroyne 

-------- Opprinnelig melding --------
Fra: Matt McManus notifications@github.com 
Dato:  
Til: punkave/grunt-dox grunt-dox@noreply.github.com 
Ko: Alexander Vassbotn Røyne-Helgesen alexander@phun-ky.net 
Emne: Re: [grunt-dox] Updated dox task to support grunt 0.4rc5 (#6) 

You make two great points.

the parentDir function is a perfect example of complete over-engineering. I realized that the other night and hadn't got around to tearing it out.
There is a disconnect between this being a multitask and dox-foundation not really supporting multiple sources. In the new example that you provided in the readme, what is the final result look like?
Hopefully I'll get a chance to pull down this change locally and play around with it.

**Comment by phun-ky** [comment]
Updated PR at dox-foundation to support multiple directories. When that PR is merged, I/you can fix this PR

**Pull request merged**
